### ISSUE TITLE
[Request] Add support for `placeholder` on `input:date`

### ISSUE THREAD

**Issue by hacknug** [wearebraid/vue-formulate#216]
As you probably know, `input:date` doesn't use a customizable placeholder but instead shows a default date format placeholder. The way most people have worked around this _issue_ is using an `input:text` that changes `type` on focus (maybe blur too if the value is empty).

Given the docs show an example using `placeholder` on `input:date` maybe we could also implement this functionality on core somehow? I understand this would only be used on old browsers without support for date-type inputs, correct?

**Comment by justin-schroeder** [comment]
Ahh, yes. hmmm that's an interesting idea, we could probably make something like that work. Im not sure if there are accessibility concerns with swapping the type like that?

**Comment by hacknug** [comment]
None that I know of but I'm no expert on the subject so… 🤷‍♂️

**Comment by justin-schroeder** [comment]
Ok, I after thinking about it more I think this one probably shouldn't end up in core, but it makes for a compelling user-land plugin, but there are a lot of stylistic challenges and other edge cases that I dont think we can assume people will understand as a default setup.

**Comment by hacknug** [comment]
Yup. Will add it to my custom controls list and hopefully I'll ship something  to workaround this on my plugin :+1:

**Comment by yf-hk** [comment]
Is there any out of the box control that we can use?

**Comment by hacknug** [comment]
No, sorry. I ended up only building custom version of the following:
- Button
- Combobox
- Password
- Pin
- Range
- Switch
- Text
- Password

I can try to find time by the end of the month to publish those although I never got to clean them up since the client put the project on hold.

**Comment by yf-hk** [comment]
Well, there is a way to put a place holder there, but it's a bit hacky:
```css
.formulate-input[data-classification='text'] {
  .formulate-input-element--date,
  .formulate-input-element--month,
  .formulate-input-element--week,
  .formulate-input-element--datetime-local {
    input {
      height: 2.875rem;
      min-height: 2.875rem; /* shim for some browsers that collapse height like ios */
  
      /* fake placeholder */
      &[type='date']::before {
        color: #a8a8a8;
        content: attr(placeholder);
        width: 100%;
      }
      &[type='date']:focus::before {
        display: none;
      }
    }
  }
  
  &[data-has-value] input::before {
    display: none;
  }
}
```
Maybe we can add that to formulate's default css?
