### ISSUE TITLE
Windows select dropdown values appear initially dimmed even though not disabled

### ISSUE THREAD

**Issue by codekiln** [wearebraid/vue-formulate#236]
In Windows, the non-disabled values of the select dropdown appear unexpectedly dimmed upon first interaction. After selecting a value, they no longer appear dimmed.

## To Reproduce

In Windows 10 (presumably other Windows versions, too), open Chrome or Firefox, go to https://vueformulate.com/guide/inputs/types/select/, and click on _Which of your children is your favorite?_.

### Expected result

The non-disabled values in drop-down should not appear dimmed in dropdown.
On Mac, this is the behavior: 
![image](https://user-images.githubusercontent.com/140930/92166646-eeb0cc80-ee06-11ea-851d-cc535ff8fb36.png)

### Actual result

The text values in the drop-down appear dimmed if an option is not yet selected. After selecting an option, the values in the drop-down no longer appear dimmed:
Chrome:
![image](https://user-images.githubusercontent.com/140930/92166815-47806500-ee07-11ea-8c6a-0e047724374e.png)
Firefox:
![image](https://user-images.githubusercontent.com/140930/92167160-e9a04d00-ee07-11ea-85fe-e88507c9243e.png)

## Device information
 - Device: Mac Laptop running Windows 10 in VirtualBox
 - Browser Chrome and Firefox, latest versions

**Comment by andrew-boyd** [comment]
Thank you for the report @codekiln, I'll look into it.

**Comment by codekiln** [comment]
Workaround: I was able to [customize the snow theme for select inputs](https://github.com/wearebraid/vue-formulate/blob/master/themes/snow/_inputs.scss#L291) with the following customization: 

```scss
@import "~@braid/vue-formulate/themes/snow/variables";
@import "~@braid/vue-formulate/themes/snow/inputs";
.formulate-input {
  &[data-classification='select'] {
    select {
      &[data-placeholder-selected] {
        color: var(--zep-black); // use my own custom color
      }
    }
  }
}

```
